import { describe, expect, test } from "bun:test";
import {
  canonicalScoreByModel,
  type ReferenceFilter,
  type ScoreField,
} from "../src/lib/canonicalScore";
import type {
  CountryCode,
  ScenarioPredictionsByVariable,
} from "../src/types";
import fixture from "./fixtures/scorer_vectors.json";

/**
 * Cross-language scorer parity.
 *
 * The fixture is generated by the Python canonical scorer
 * (`policybench export-scorer-vectors` → `policybench/scorer_vectors.py`). Each
 * vector carries a synthetic `scenarioPredictions` payload plus the per-model
 * scores Python produced. This suite replays every payload through the
 * TypeScript scorer and asserts it reproduces those scores, so any drift between
 * the two implementations fails CI.
 *
 * One vector class (`tsDivergence: true`) pins a documented, narrow
 * disagreement: when a household's entire kept active set has zero output-group
 * weight, Python counts the household (score 0) while TypeScript skips it. Those
 * vectors assert the *TypeScript* result (and that it genuinely differs from
 * Python), keeping the gap visible rather than hidden.
 */

type WeightsView = "household" | "aggregate" | "equal";

interface ScorerVector {
  name: string;
  description: string;
  country: string;
  weightsView: WeightsView;
  programFilter: string[];
  referenceFilter: ReferenceFilter;
  field: ScoreField;
  scenarioPredictions: Record<string, ScenarioPredictionsByVariable>;
  globalWeights: Record<WeightsView, Record<string, number>>;
  expectedScores: Record<string, number>;
  tsDivergence: boolean;
  divergenceReason?: string;
  zeroWeightScenarios?: string[];
  typescriptScores?: Record<string, number>;
}

interface ScorerFixture {
  version: number;
  seed: number;
  tolerance: number;
  description: string;
  vectors: ScorerVector[];
}

const data = fixture as ScorerFixture;
const tolerance = data.tolerance;

function runVector(vector: ScorerVector): Map<string, number> {
  return canonicalScoreByModel({
    scenarioPredictions: vector.scenarioPredictions,
    weights: vector.globalWeights[vector.weightsView],
    country: vector.country as CountryCode,
    activeProgramIds: new Set(vector.programFilter),
    referenceFilter: vector.referenceFilter,
    field: vector.field,
  });
}

function assertScoresMatch(
  actual: Map<string, number>,
  expected: Record<string, number>,
): void {
  const expectedModels = Object.keys(expected).sort();
  const actualModels = [...actual.keys()].sort();
  // The set of scored models must agree exactly — a model present on one side
  // and absent on the other is itself a parity failure.
  expect(actualModels).toEqual(expectedModels);
  for (const model of expectedModels) {
    const got = actual.get(model);
    expect(got).toBeDefined();
    expect(Math.abs((got as number) - expected[model])).toBeLessThanOrEqual(
      tolerance,
    );
  }
}

describe("canonical scorer parity (TypeScript vs Python fixture)", () => {
  test("fixture loads with the expected shape", () => {
    expect(data.version).toBeGreaterThanOrEqual(1);
    expect(data.vectors.length).toBeGreaterThanOrEqual(24);
    expect(tolerance).toBeGreaterThan(0);
  });

  const agreeing = data.vectors.filter((vector) => !vector.tsDivergence);
  const diverging = data.vectors.filter((vector) => vector.tsDivergence);

  test.each(agreeing.map((vector) => [vector.name, vector] as const))(
    "reproduces Python scores: %s",
    (_name, vector) => {
      assertScoresMatch(runVector(vector), vector.expectedScores);
    },
  );

  describe("documented zero-weight divergence", () => {
    test("there is at least one flagged divergence vector", () => {
      expect(diverging.length).toBeGreaterThanOrEqual(1);
    });

    test.each(diverging.map((vector) => [vector.name, vector] as const))(
      "matches the recorded TypeScript behavior, which differs from Python: %s",
      (_name, vector) => {
        const actual = runVector(vector);
        const typescriptScores = vector.typescriptScores ?? {};
        // TypeScript skips zero-denominator households, so for a single
        // zero-weight active program it scores no households and omits every
        // model.
        assertScoresMatch(actual, typescriptScores);
        // And confirm the divergence is real: Python expected non-empty scores
        // (all 0) for models the TypeScript scorer drops.
        expect(Object.keys(vector.expectedScores).length).toBeGreaterThan(0);
        expect(actual.size).not.toBe(Object.keys(vector.expectedScores).length);
        expect(vector.divergenceReason).toBeTruthy();
      },
    );
  });
});
