<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.23">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="PolicyEngine">

<title>PolicyBench</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
.display.math{display: block; text-align: center; margin: 0.5rem auto;}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-html-759c0ece14ff2c0bb30ede3498dcac91.min.css" rel="stylesheet" append-hash="true" data-mode="light">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-226bd0f977fa82dfae4534cac220d79a.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="pe-tokens.css">
<link rel="stylesheet" href="policybench-theme.css">
<meta name="citation_title" content="PolicyBench">
<meta name="citation_author" content="PolicyEngine ">
<meta name="citation_language" content="en">
<meta name="citation_reference" content="citation_title=PolicyBench;,citation_author=PolicyEngine;,citation_publication_date=2026;,citation_cover_date=2026;,citation_year=2026;,citation_publisher=https://policybench.org;">
<meta name="citation_reference" content="citation_title=TaxCalcBench: Evaluating frontier models on the tax calculation task;,citation_author=Meenakshi Mahesh;,citation_author=Elliott Ash;,citation_author=Elsen Tan;,citation_author=Aman Madaan;,citation_publication_date=2025;,citation_cover_date=2025;,citation_year=2025;,citation_fulltext_html_url=https://arxiv.org/abs/2507.16126;,citation_journal_title=arXiv preprint arXiv:2507.16126;">
<meta name="citation_reference" content="citation_title=Performance of LLMs on VITA test: Potential for AI-assisted tax returns for low income taxpayers;,citation_author=Catherine Shanahan;,citation_author=Emma McCarthy;,citation_author=Yan Zhao;,citation_author=Wesley H. Holliday;,citation_author=Jenny Zhao;,citation_author=Janet Ainsworth;,citation_author=Harry Surden;,citation_publication_date=2025;,citation_cover_date=2025;,citation_year=2025;,citation_fulltext_html_url=https://link.springer.com/article/10.1007/s10506-025-09465-7;,citation_doi=10.1007/s10506-025-09465-7;,citation_journal_title=Artificial Intelligence and Law;">
<meta name="citation_reference" content="citation_title=Factoring statutory reasoning as language understanding challenges;,citation_author=Nils Holzenberger;,citation_author=Benjamin Van Durme;,citation_author=Sarah Lawsky;,citation_author=Kyle Richardson;,citation_publication_date=2021;,citation_cover_date=2021;,citation_year=2021;,citation_fulltext_html_url=https://arxiv.org/abs/2105.07903;,citation_journal_title=arXiv preprint arXiv:2105.07903;">
<meta name="citation_reference" content="citation_title=LegalBench: A collaboratively built benchmark for measuring legal reasoning in large language models;,citation_author=Neel Guha;,citation_author=Julian Nyarko;,citation_author=Daniel E. Ho;,citation_author=others;,citation_publication_date=2023;,citation_cover_date=2023;,citation_year=2023;,citation_fulltext_html_url=https://arxiv.org/abs/2308.11462;,citation_journal_title=arXiv preprint arXiv:2308.11462;">
<meta name="citation_reference" content="citation_title=RuleArena: A benchmark for rule-guided reasoning with LLMs in real-world scenarios;,citation_author=Chan Kim;,citation_author=Jiseung Kim;,citation_author=Jihyung Choi;,citation_author=Juho Lee;,citation_author=Seongyeon Ryu;,citation_author=Sangki Yoon;,citation_author=others;,citation_publication_date=2024;,citation_cover_date=2024;,citation_year=2024;,citation_fulltext_html_url=https://arxiv.org/abs/2412.08972;,citation_journal_title=arXiv preprint arXiv:2412.08972;">
<meta name="citation_reference" content="citation_title=Training verifiers to solve math word problems;,citation_author=Karl Cobbe;,citation_author=Vineet Kosaraju;,citation_author=Mohammad Bavarian;,citation_author=Mark Chen;,citation_author=Heewoo Jun;,citation_author=Lukasz Kaiser;,citation_author=Matthias Plappert;,citation_author=Jerry Tworek;,citation_author=Jacob Hilton;,citation_author=Reiichiro Nakano;,citation_author=Christopher Hesse;,citation_author=John Schulman;,citation_publication_date=2021;,citation_cover_date=2021;,citation_year=2021;,citation_fulltext_html_url=https://arxiv.org/abs/2110.14168;,citation_journal_title=arXiv preprint arXiv:2110.14168;">
<meta name="citation_reference" content="citation_title=Measuring mathematical problem solving with the MATH dataset;,citation_author=Dan Hendrycks;,citation_author=Collin Burns;,citation_author=Saurav Kadavath;,citation_author=Akul Arora;,citation_author=Steven Basart;,citation_author=Eric Tang;,citation_author=Dawn Song;,citation_author=Jacob Steinhardt;,citation_publication_date=2021;,citation_cover_date=2021;,citation_year=2021;,citation_fulltext_html_url=https://arxiv.org/abs/2103.03874;,citation_conference_title=NeurIPS datasets and benchmarks track;">
<meta name="citation_reference" content="citation_title=A careful examination of large language model performance on grade school arithmetic;,citation_author=Dimitris Bertsimas;,citation_author=Arthur Delarue;,citation_author=Alexander Paskov;,citation_author=others;,citation_publication_date=2024;,citation_cover_date=2024;,citation_year=2024;,citation_fulltext_html_url=https://arxiv.org/abs/2405.00332;,citation_journal_title=arXiv preprint arXiv:2405.00332;">
<meta name="citation_reference" content="citation_title=Time to revisit exact match: Evaluating temporal question answering with numeric error metrics;,citation_author=Xinyue Zhou;,citation_author=others;,citation_publication_date=2025;,citation_cover_date=2025;,citation_year=2025;,citation_fulltext_html_url=https://arxiv.org/abs/2509.16720;,citation_journal_title=arXiv preprint arXiv:2509.16720;">
<meta name="citation_reference" content="citation_title=FinQA: A dataset of numerical reasoning over financial data;,citation_author=Zhiyu Chen;,citation_author=Wenhu Chen;,citation_author=Charese Smiley;,citation_author=Sameena Shah;,citation_author=Iana Borova;,citation_author=Derek Langdon;,citation_author=Reham Moussa;,citation_author=Matt Beane;,citation_author=Ting-Hao Kenneth Huang;,citation_author=Bryan Routledge;,citation_author=others;,citation_publication_date=2021;,citation_cover_date=2021;,citation_year=2021;,citation_fulltext_html_url=https://arxiv.org/abs/2109.00122;,citation_journal_title=arXiv preprint arXiv:2109.00122;">
<meta name="citation_reference" content="citation_title=TAT-QA: A question answering benchmark on a hybrid of tabular and textual content in finance;,citation_author=Fengbin Zhu;,citation_author=Wenqiang Lei;,citation_author=Youcheng Huang;,citation_author=Chao Wang;,citation_author=Shujie Zhang;,citation_author=Hongjie Wang;,citation_author=Vincent Chen;,citation_author=others;,citation_publication_date=2021;,citation_cover_date=2021;,citation_year=2021;,citation_fulltext_html_url=https://arxiv.org/abs/2105.07624;,citation_journal_title=arXiv preprint arXiv:2105.07624;">
<meta name="citation_reference" content="citation_title=StructuredRAG: JSON response formatting with large language models;,citation_author=Connor Shorten;,citation_author=Charles Pierse;,citation_author=Thomas Benjamin Smith;,citation_author=Erika Cardenas;,citation_author=Akanksha Sharma;,citation_author=John Trengrove;,citation_author=Bob Luijt;,citation_publication_date=2024;,citation_cover_date=2024;,citation_year=2024;,citation_fulltext_html_url=https://arxiv.org/abs/2408.11061;,citation_doi=10.48550/arXiv.2408.11061;,citation_journal_title=arXiv preprint arXiv:2408.11061;">
<meta name="citation_reference" content="citation_title=EUROMOD: The european union tax-benefit microsimulation model;,citation_author=Holly Sutherland;,citation_author=Francesco Figari;,citation_author=Ruth Hancock;,citation_author=Manos Matsaganis;,citation_author=Alari Paulus;,citation_author=Iva Tasseva;,citation_author=Alessandra Tumino;,citation_author=Paola De Agostini;,citation_publication_date=2023;,citation_cover_date=2023;,citation_year=2023;,citation_fulltext_html_url=https://microsimulation.pub/articles/00075;,citation_journal_title=International Journal of Microsimulation;">
<meta name="citation_reference" content="citation_title=Improving the accuracy of UK tax-benefit microsimulation with machine learning;,citation_author=Nikhil Woodruff;,citation_author=Max Ghenis;,citation_publication_date=2026;,citation_cover_date=2026;,citation_year=2026;,citation_fulltext_html_url=https://policyengine.org/uk_data_enhancement.pdf;,citation_publisher=PolicyEngine technical paper;">
<meta name="citation_reference" content="citation_title=Evaluating a genAI-powered assistive chatbot for caseworkers;,citation_author=Nava Labs;,citation_publication_date=2026;,citation_cover_date=2026;,citation_year=2026;,citation_fulltext_html_url=https://www.navapbc.com/case-studies/evaluating-ai-assistive-chatbot-caseworkers;,citation_publisher=Case study;">
<meta name="citation_reference" content="citation_title=Experimenting with AI-powered tools in public benefits;,citation_author=Nava Labs;,citation_publication_date=2025;,citation_cover_date=2025;,citation_year=2025;,citation_fulltext_html_url=https://www.navapbc.com/case-studies/ai-tools-public-benefits;,citation_publisher=Case study;">
<meta name="citation_reference" content="citation_title=Building and automating comprehensive LLM evaluation framework for SNAP benefits;,citation_author=ZenML LLMOps Database;,citation_publication_date=2025;,citation_cover_date=2025;,citation_year=2025;,citation_fulltext_html_url=https://www.zenml.io/llmops-database/building-and-automating-comprehensive-llm-evaluation-framework-for-snap-benefits;,citation_publisher=Industry writeup;">
</head>

<body>


<header id="title-block-header">
<h1 class="title">PolicyBench</h1>
<p class="subtitle">Benchmarking tax-and-benefit reasoning in frontier language models</p>
<p class="author">PolicyEngine</p>

</header>

<nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract">Abstract</a></li>
  <li><a href="#introduction" id="toc-introduction">Introduction</a></li>
  <li><a href="#related-work" id="toc-related-work">Related work</a></li>
  <li><a href="#benchmark-design" id="toc-benchmark-design">Benchmark design</a></li>
  <li><a href="#data-and-scenario-construction" id="toc-data-and-scenario-construction">Data and scenario construction</a>
  <ul>
  <li><a href="#united-states" id="toc-united-states">United States</a></li>
  <li><a href="#united-kingdom" id="toc-united-kingdom">United Kingdom</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results">Results</a>
  <ul>
  <li><a href="#united-states-leaderboard" id="toc-united-states-leaderboard">United States leaderboard</a></li>
  <li><a href="#united-kingdom-leaderboard" id="toc-united-kingdom-leaderboard">United Kingdom leaderboard</a></li>
  <li><a href="#global-shared-model-leaderboard" id="toc-global-shared-model-leaderboard">Global shared-model leaderboard</a></li>
  <li><a href="#hardest-benchmark-targets" id="toc-hardest-benchmark-targets">Hardest benchmark targets</a></li>
  </ul></li>
  <li><a href="#failure-modes" id="toc-failure-modes">Failure modes</a></li>
  <li><a href="#limitations" id="toc-limitations">Limitations</a></li>
  <li><a href="#conclusion" id="toc-conclusion">Conclusion</a></li>
  </ul>
</nav>
<h2 id="abstract" class="anchored">Abstract</h2>
<p>PolicyBench evaluates whether frontier language models can estimate household tax and benefit outputs from household facts without tools. The benchmark covers the United States and the United Kingdom, uses nationally calibrated household scenarios, and scores outputs with a bounded <code>0-100</code> metric. In the frozen snapshot used for this manuscript (2026-04-04), the top US model is gemini-3.1-pro-preview at 73.3, the top UK model is grok-4.20 at 83.0, and the top shared global model is gemini-3.1-pro-preview at 78.0. In both countries, the lowest-scoring outputs are tax-base variables rather than benefits or credits. The live benchmark is available at <a href="https://policybench.org" class="uri">https://policybench.org</a>.</p>
<h2 id="introduction" class="anchored">Introduction</h2>
<p>Household tax-and-benefit estimation sits between arithmetic and policy discussion. Each case has numeric labels, but generating those labels requires filing status, household composition, income concepts, program thresholds, and jurisdiction-specific rules. PolicyBench measures whether models can map household records to those outputs.</p>
<p>Most current language-model evaluations do not test this mapping directly. General math benchmarks emphasize symbolic manipulation and exact final answers <span class="citation" data-cites="cobbe2021training hendrycks2021math">(Cobbe et al. 2021; Hendrycks et al. 2021)</span>, while generic question-answering benchmarks emphasize recall or instruction following. PolicyBench instead asks whether models can transform household facts into policy outputs without access to tools or simulators.</p>
<p>This matters for public-facing calculators, analyst workflows, and tax-preparation or screening systems. The benchmark is intended to separate verbal policy fluency from household-level quantitative prediction.</p>
<h2 id="related-work" class="anchored">Related work</h2>
<p>The most relevant prior work is tax and statutory reasoning. SARA frames statutory interpretation, including tax-relevant rule application, as a language-understanding problem <span class="citation" data-cites="holzenberger2021sara">(Holzenberger et al. 2021)</span>. LegalBench broadens this view and includes tax-oriented numeric tasks such as <code>sara_numeric</code> <span class="citation" data-cites="guha2023legalbench">(Guha et al. 2023)</span>. RuleArena evaluates rule-guided reasoning in regulation-style settings <span class="citation" data-cites="kim2024rulearena">(Kim et al. 2024)</span>, and TaxCalcBench evaluates frontier models on tax calculation from structured return-like inputs <span class="citation" data-cites="taxcalcbench2025">(Mahesh et al. 2025)</span>. Shanahan et al.&nbsp;report a similar split on the VITA test: models do better on tax knowledge questions than on open-ended calculation tasks <span class="citation" data-cites="shanahan2025vita">(Shanahan et al. 2025)</span>.</p>
<p>PolicyBench also sits within a broader literature on quantitative reasoning benchmarks. Canonical math evaluations such as GSM8K and MATH normalized exact final-answer scoring for numeric tasks <span class="citation" data-cites="cobbe2021training hendrycks2021math">(Cobbe et al. 2021; Hendrycks et al. 2021)</span>. That norm is less natural for continuous-valued policy outputs, where being within 1 percent is closer than being off by an order of magnitude. Recent work has questioned pure exact-match scoring in numeric QA and temporal reasoning, arguing for error-aware metrics instead <span class="citation" data-cites="zhou2025tempanswerqa">(Zhou et al. 2025)</span>. PolicyBench follows that direction by combining exactness with near-miss thresholds rather than collapsing everything into exact match alone.</p>
<p>Finance-domain benchmarks provide another relevant precedent. FinQA and TAT-QA both show that realistic quantitative reasoning often requires combining structured numbers with domain knowledge rather than solving stylized school-math problems <span class="citation" data-cites="chen2021finqa zhu2021tatqa">(Chen et al. 2021; Zhu et al. 2021)</span>. PolicyBench differs in that its reference outputs are generated by executable tax-benefit microsimulation rather than annotated document questions, but the underlying motivation is similar: domain-specific quantitative reasoning deserves dedicated evaluation.</p>
<p>Finally, PolicyBench depends on two infrastructure literatures that are not themselves LLM benchmarks. One is structured-output reliability, since the benchmark relies on multi-output JSON responses and parse coverage rather than free-form prose <span class="citation" data-cites="shorten2024structuredrag">(Shorten et al. 2024)</span>. The other is tax-benefit microsimulation, where systems such as EUROMOD provide the methodological precedent for evaluating policy rules over household microdata <span class="citation" data-cites="sutherland2023euromod">(Sutherland et al. 2023)</span>. The UK side of PolicyBench also builds on PolicyEngine’s recent work on survey-backed calibration and imputation <span class="citation" data-cites="policyengineukdata2026">(Woodruff and Ghenis 2026)</span>. There is also operational work on applying and evaluating AI systems in public-benefits settings, including caseworker-assist and SNAP-focused evaluations <span class="citation" data-cites="nava2026caseworker nava2025benefits propel2025snap">(Nava Labs 2026, 2025; ZenML LLMOps Database 2025)</span>. We are not aware of a public cross-model benchmark over household-level benefit outputs.</p>
<h2 id="benchmark-design" class="anchored">Benchmark design</h2>
<p>PolicyBench asks models to predict all benchmark outputs for a household in a single structured response. One response per household reduces repeated prompt cost and keeps the task at the household-return level rather than turning it into a sequence of unrelated one-output calls.</p>
<p>The benchmark uses a bounded <code>0-100</code> score. For amount variables, the score averages four hit rates:</p>
<ol type="1">
<li>exact</li>
<li>within 1%</li>
<li>within 5%</li>
<li>within 10%</li>
</ol>
<p>For binary outputs, the score is exact accuracy. This keeps <code>100</code> as the ceiling while still giving partial credit for near misses on amount outputs. PolicyBench also tracks mean absolute error and related diagnostics, but those are secondary to the bounded score. This choice preserves exact-match comparability while avoiding the failure mode that recent numeric-evaluation papers have criticized <span class="citation" data-cites="zhou2025tempanswerqa">(Zhou et al. 2025)</span>.</p>
<p>The benchmark distinguishes between <strong>benchmark runs</strong> and <strong>diagnostic runs</strong>. Benchmark runs are the canonical leaderboard artifacts. Diagnostic runs use smaller sidecar samples and may request optional explanations. Those explanation runs are used for qualitative analysis and are not part of the headline ranking.</p>
<p>PolicyBench also has an earlier archived tool-assisted pilot. That condition used a single untuned function-calling contract rather than a multi-step agent setup. The only tool was <code>calculate_policy(household, variable, year)</code>, where <code>household</code> was a standard PolicyEngine-US household JSON object and the archived scenarios supplied only basic fields needed for those tests: person ages, employment income, and household state. The prompt was a short instruction to calculate one output, use the tool with the given variable name and year, and return the numeric result from the tool. The archived US run covers <code>4,200</code> predictions (<code>100</code> households x <code>14</code> outputs x <code>3</code> models: Claude Opus, Claude Sonnet, and GPT-5.2), and all <code>4,200</code> predictions match the simulator reference values exactly. We do not mix that condition into the current leaderboard because it measures whether the model can route the request to the simulator and use the returned value, not whether it can estimate the output without tools.</p>
<h2 id="data-and-scenario-construction" class="anchored">Data and scenario construction</h2>
<h3 id="united-states" class="anchored">United States</h3>
<p>The US benchmark is built from Enhanced CPS-derived households using PolicyEngine US. The sampled households are filtered to keep a single-tax-unit structure while retaining variation in filing status, household composition, and income sources. Prompts include nonzero promptable raw inputs across relevant entities rather than a hand-curated summary, so the models see many of the same facts the simulator receives.</p>
<p>The current US release evaluates 13 outputs spanning federal tax, credits, benefits, and state-tax quantities. These include federal adjusted gross income, tax before refundable credits, EITC, CTC, SNAP, SSI, and multiple state-tax outputs.</p>
<h3 id="united-kingdom" class="anchored">United Kingdom</h3>
<p>The UK benchmark is built from a calibrated public transfer dataset scored through PolicyEngine UK. The current public build starts from a public export of benchmark-compatible households from PolicyEngine US Enhanced CPS, maps those records into UK-facing inputs, and recalibrates them to selected UK targets. This creates a public UK benchmark path without publishing restricted household microdata. The current UK release evaluates six outputs: income tax, national insurance, child benefit, universal credit, pension credit, and personal independence payment.</p>
<p>The UK data path is more synthetic than the enhanced FRS pipeline, so the benchmark should not be read as a substitute for native UK microdata work. It supports the current public cross-country benchmark, but it is not equivalent to an enhanced-FRS-based benchmark <span class="citation" data-cites="sutherland2023euromod policyengineukdata2026">(Sutherland et al. 2023; Woodruff and Ghenis 2026)</span>.</p>
<h2 id="results" class="anchored">Results</h2>
<h3 id="united-states-leaderboard" class="anchored">United States leaderboard</h3>
<p>The US leaderboard for the frozen manuscript snapshot is shown in <a href="#tbl-us-top" class="quarto-xref">Table&nbsp;1</a>. The top three models in that snapshot are gemini-3.1-pro-preview (73.4), grok-4.20 (71.7), and gemini-3-flash-preview (69.5).</p>
<div class="cell" data-execution_count="2">
<div id="tbl-us-top" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="2">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-us-top-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Top US benchmark models in the current release.
</figcaption>
<div aria-describedby="tbl-us-top-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="2">
<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

<table class="dataframe do-not-create-environment cell caption-top" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header" style="text-align: right;">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Model</th>
<th data-quarto-table-cell-role="th">Score</th>
<th data-quarto-table-cell-role="th">Exact</th>
<th data-quarto-table-cell-role="th">Within 10%</th>
<th data-quarto-table-cell-role="th">Parsed</th>
<th data-quarto-table-cell-role="th">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>gemini-3.1-pro-preview</td>
<td>73.4</td>
<td>67.6</td>
<td>80.4</td>
<td>12974</td>
<td>12974</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>grok-4.20</td>
<td>71.7</td>
<td>66.3</td>
<td>78.5</td>
<td>13000</td>
<td>13000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>gemini-3-flash-preview</td>
<td>69.5</td>
<td>64.5</td>
<td>75.7</td>
<td>13000</td>
<td>13000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>gpt-5.4</td>
<td>67.2</td>
<td>62.7</td>
<td>72.7</td>
<td>13000</td>
<td>13000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>claude-opus-4.6</td>
<td>66.2</td>
<td>61.4</td>
<td>71.9</td>
<td>12558</td>
<td>12558</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<h3 id="united-kingdom-leaderboard" class="anchored">United Kingdom leaderboard</h3>
<p>The UK leaderboard for the frozen manuscript snapshot is shown in <a href="#tbl-uk-top" class="quarto-xref">Table&nbsp;2</a>. The top three models in that snapshot are grok-4.20 (83.0), gemini-3.1-pro-preview (82.6), and gemini-3-flash-preview (71.6).</p>
<div class="cell" data-execution_count="3">
<div id="tbl-uk-top" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="3">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-uk-top-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Top UK benchmark models in the current release.
</figcaption>
<div aria-describedby="tbl-uk-top-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="3">
<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

<table class="dataframe do-not-create-environment cell caption-top" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header" style="text-align: right;">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Model</th>
<th data-quarto-table-cell-role="th">Score</th>
<th data-quarto-table-cell-role="th">Exact</th>
<th data-quarto-table-cell-role="th">Within 10%</th>
<th data-quarto-table-cell-role="th">Parsed</th>
<th data-quarto-table-cell-role="th">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>grok-4.20</td>
<td>83.0</td>
<td>76.0</td>
<td>90.0</td>
<td>6000</td>
<td>6000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>gemini-3.1-pro-preview</td>
<td>82.6</td>
<td>74.7</td>
<td>90.5</td>
<td>6000</td>
<td>6000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>gemini-3-flash-preview</td>
<td>71.6</td>
<td>64.4</td>
<td>79.5</td>
<td>6000</td>
<td>6000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>gpt-5.4</td>
<td>68.9</td>
<td>62.7</td>
<td>76.1</td>
<td>6000</td>
<td>6000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>gemini-3.1-flash-lite-preview</td>
<td>68.7</td>
<td>62.9</td>
<td>76.3</td>
<td>6000</td>
<td>6000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<h3 id="global-shared-model-leaderboard" class="anchored">Global shared-model leaderboard</h3>
<p>The global leaderboard averages US and UK scores for the models that have been run in both countries. In the frozen manuscript snapshot, the top three are gemini-3.1-pro-preview (78.0), grok-4.20 (77.3), and gemini-3-flash-preview (70.6). The global table summarizes cross-country performance; the country tables identify the outputs driving the differences.</p>
<div class="cell" data-execution_count="4">
<div id="tbl-global-top" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="4">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-global-top-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Global shared-model leaderboard across US and UK runs.
</figcaption>
<div aria-describedby="tbl-global-top-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="4">
<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

<table class="dataframe do-not-create-environment cell caption-top" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header" style="text-align: right;">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Model</th>
<th data-quarto-table-cell-role="th">Score</th>
<th data-quarto-table-cell-role="th">Exact</th>
<th data-quarto-table-cell-role="th">Within 10%</th>
<th data-quarto-table-cell-role="th">Parsed</th>
<th data-quarto-table-cell-role="th">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>gemini-3.1-pro-preview</td>
<td>78.0</td>
<td>71.1</td>
<td>85.4</td>
<td>18974</td>
<td>18974</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>grok-4.20</td>
<td>77.3</td>
<td>71.2</td>
<td>84.2</td>
<td>19000</td>
<td>19000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>gemini-3-flash-preview</td>
<td>70.6</td>
<td>64.4</td>
<td>77.6</td>
<td>19000</td>
<td>19000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>gpt-5.4</td>
<td>68.0</td>
<td>62.7</td>
<td>74.4</td>
<td>19000</td>
<td>19000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>gemini-3.1-flash-lite-preview</td>
<td>67.3</td>
<td>62.2</td>
<td>73.9</td>
<td>19000</td>
<td>19000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>claude-opus-4.6</td>
<td>67.1</td>
<td>61.7</td>
<td>73.8</td>
<td>18533</td>
<td>18558</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>claude-sonnet-4.6</td>
<td>66.4</td>
<td>61.9</td>
<td>72.1</td>
<td>18974</td>
<td>18974</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>gpt-5.4-mini</td>
<td>64.5</td>
<td>62.3</td>
<td>67.2</td>
<td>19000</td>
<td>19000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>claude-haiku-4.5</td>
<td>63.2</td>
<td>60.9</td>
<td>66.5</td>
<td>19000</td>
<td>19000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">9</td>
<td>gpt-5.4-nano</td>
<td>61.8</td>
<td>60.8</td>
<td>63.2</td>
<td>19000</td>
<td>19000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<h3 id="hardest-benchmark-targets" class="anchored">Hardest benchmark targets</h3>
<p>The lowest-scoring US variables are tax-base and state-tax quantities rather than benefits. As shown in <a href="#tbl-us-hardest" class="quarto-xref">Table&nbsp;4</a>, household state income tax scores <code>31.5</code>, state AGI scores <code>32.9</code>, federal income tax before refundable credits scores <code>33.2</code>, and adjusted gross income scores <code>37.1</code>. By comparison, EITC scores <code>86.3</code>, SSI scores <code>93.1</code>, and free school meals scores <code>94.1</code>.</p>
<div class="cell" data-execution_count="5">
<div id="tbl-us-hardest" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="5">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-us-hardest-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Hardest US variables by bounded score.
</figcaption>
<div aria-describedby="tbl-us-hardest-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="5">
<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

<table class="dataframe do-not-create-environment cell caption-top" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header" style="text-align: right;">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Variable</th>
<th data-quarto-table-cell-role="th">Score</th>
<th data-quarto-table-cell-role="th">Exact</th>
<th data-quarto-table-cell-role="th">Within 10%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>household_state_income_tax</td>
<td>31.9</td>
<td>28.2</td>
<td>37.3</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">10</td>
<td>state_agi</td>
<td>34.0</td>
<td>20.6</td>
<td>47.5</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">5</td>
<td>income_tax_before_refundable_credits</td>
<td>34.0</td>
<td>30.3</td>
<td>39.9</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">0</td>
<td>adjusted_gross_income</td>
<td>39.6</td>
<td>21.3</td>
<td>57.7</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">11</td>
<td>state_income_tax_before_refundable_credits</td>
<td>40.4</td>
<td>36.4</td>
<td>46.1</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p>The same pattern appears in the UK run. Income tax scores <code>32.2</code> and national insurance scores <code>51.9</code>. Child benefit scores <code>77.3</code>, universal credit scores <code>77.6</code>, PIP scores <code>84.0</code>, and pension credit scores <code>88.4</code>.</p>
<div class="cell" data-execution_count="6">
<div id="tbl-uk-hardest" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="6">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-uk-hardest-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Hardest UK variables by bounded score.
</figcaption>
<div aria-describedby="tbl-uk-hardest-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="6">
<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

<table class="dataframe do-not-create-environment cell caption-top" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header" style="text-align: right;">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Variable</th>
<th data-quarto-table-cell-role="th">Score</th>
<th data-quarto-table-cell-role="th">Exact</th>
<th data-quarto-table-cell-role="th">Within 10%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">1</td>
<td>income_tax</td>
<td>34.8</td>
<td>25.4</td>
<td>45.8</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2</td>
<td>national_insurance</td>
<td>55.3</td>
<td>50.6</td>
<td>61.5</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">5</td>
<td>universal_credit</td>
<td>77.7</td>
<td>76.9</td>
<td>78.8</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">0</td>
<td>child_benefit</td>
<td>78.1</td>
<td>70.7</td>
<td>86.1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>pip</td>
<td>84.9</td>
<td>79.4</td>
<td>90.8</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<h2 id="failure-modes" class="anchored">Failure modes</h2>
<p>The benchmark surfaces a few recurring failure patterns.</p>
<p>First, models miss positive tax quantities more often than zero cases. In the US, the four lowest-scoring variables are household state income tax, state AGI, federal income tax before refundable credits, and adjusted gross income. These outputs require the model to choose the right income concepts and exclusions before applying any final subtraction.</p>
<p>Second, the UK benchmark shows the same split between benefits and tax. Income tax and national insurance score below the four benefit outputs in the frozen manuscript snapshot. This suggests that the models handle broad program thresholds more reliably than detailed tax-liability calculations.</p>
<p>Third, structured-output reliability still affects the ranking. Some provider-specific gaps reflect tool or JSON contract reliability in addition to policy reasoning quality. For example, Claude Opus 4.6 parses 5,975 of 6,000 UK rows in the frozen manuscript snapshot. PolicyBench therefore tracks coverage and parse rates alongside accuracy <span class="citation" data-cites="shorten2024structuredrag">(Shorten et al. 2024)</span>.</p>
<h2 id="limitations" class="anchored">Limitations</h2>
<p>PolicyBench is not a substitute for a production tax-and-benefit calculator. Several caveats matter:</p>
<ul>
<li>cost reporting is still reconstructed from provider token usage rather than invoice truth</li>
<li>model rankings can reflect output-contract reliability as well as policy reasoning</li>
<li>the public UK calibrated dataset is not equivalent to enhanced FRS quality</li>
<li>benchmark success should not be interpreted as policy-advice readiness</li>
</ul>
<p>The current paper is therefore an evaluation of model performance under a specific structured-output benchmark, not a general certification of tax or benefit competence.</p>
<h2 id="conclusion" class="anchored">Conclusion</h2>
<p>PolicyBench shows a consistent pattern across both countries. Benefit outputs score above tax-base outputs, while the lowest-scoring variables are adjusted gross income, state-tax quantities, income tax, and national insurance. In the frozen manuscript snapshot, gemini-3.1-pro-preview is the top-scoring US model and grok-4.20 is the top-scoring UK model.</p>
<p>Next steps are to expand diagnostics, extend country coverage, and tighten the data and scoring pipelines so that the leaderboard is driven less by output-format reliability and more by policy reasoning.</p>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-chen2021finqa" class="csl-entry" role="listitem">
Chen, Zhiyu, Wenhu Chen, Charese Smiley, Sameena Shah, Iana Borova, Derek Langdon, Reham Moussa, et al. 2021. <span>“FinQA: A Dataset of Numerical Reasoning over Financial Data.”</span> <em>arXiv Preprint arXiv:2109.00122</em>. <a href="https://arxiv.org/abs/2109.00122">https://arxiv.org/abs/2109.00122</a>.
</div>
<div id="ref-cobbe2021training" class="csl-entry" role="listitem">
Cobbe, Karl, Vineet Kosaraju, Mohammad Bavarian, Mark Chen, Heewoo Jun, Lukasz Kaiser, Matthias Plappert, et al. 2021. <span>“Training Verifiers to Solve Math Word Problems.”</span> <em>arXiv Preprint arXiv:2110.14168</em>. <a href="https://arxiv.org/abs/2110.14168">https://arxiv.org/abs/2110.14168</a>.
</div>
<div id="ref-guha2023legalbench" class="csl-entry" role="listitem">
Guha, Neel, Julian Nyarko, Daniel E. Ho, et al. 2023. <span>“LegalBench: A Collaboratively Built Benchmark for Measuring Legal Reasoning in Large Language Models.”</span> <em>arXiv Preprint arXiv:2308.11462</em>. <a href="https://arxiv.org/abs/2308.11462">https://arxiv.org/abs/2308.11462</a>.
</div>
<div id="ref-hendrycks2021math" class="csl-entry" role="listitem">
Hendrycks, Dan, Collin Burns, Saurav Kadavath, Akul Arora, Steven Basart, Eric Tang, Dawn Song, and Jacob Steinhardt. 2021. <span>“Measuring Mathematical Problem Solving with the <span>MATH</span> Dataset.”</span> In <em>NeurIPS Datasets and Benchmarks Track</em>. <a href="https://arxiv.org/abs/2103.03874">https://arxiv.org/abs/2103.03874</a>.
</div>
<div id="ref-holzenberger2021sara" class="csl-entry" role="listitem">
Holzenberger, Nils, Benjamin Van Durme, Sarah Lawsky, and Kyle Richardson. 2021. <span>“Factoring Statutory Reasoning as Language Understanding Challenges.”</span> <em>arXiv Preprint arXiv:2105.07903</em>. <a href="https://arxiv.org/abs/2105.07903">https://arxiv.org/abs/2105.07903</a>.
</div>
<div id="ref-kim2024rulearena" class="csl-entry" role="listitem">
Kim, Chan, Jiseung Kim, Jihyung Choi, Juho Lee, Seongyeon Ryu, Sangki Yoon, et al. 2024. <span>“RuleArena: A Benchmark for Rule-Guided Reasoning with <span>LLMs</span> in Real-World Scenarios.”</span> <em>arXiv Preprint arXiv:2412.08972</em>. <a href="https://arxiv.org/abs/2412.08972">https://arxiv.org/abs/2412.08972</a>.
</div>
<div id="ref-taxcalcbench2025" class="csl-entry" role="listitem">
Mahesh, Meenakshi, Elliott Ash, Elsen Tan, and Aman Madaan. 2025. <span>“TaxCalcBench: Evaluating Frontier Models on the Tax Calculation Task.”</span> <em>arXiv Preprint arXiv:2507.16126</em>. <a href="https://arxiv.org/abs/2507.16126">https://arxiv.org/abs/2507.16126</a>.
</div>
<div id="ref-nava2025benefits" class="csl-entry" role="listitem">
Nava Labs. 2025. <span>“Experimenting with <span>AI</span>-Powered Tools in Public Benefits.”</span> Case study. <a href="https://www.navapbc.com/case-studies/ai-tools-public-benefits">https://www.navapbc.com/case-studies/ai-tools-public-benefits</a>.
</div>
<div id="ref-nava2026caseworker" class="csl-entry" role="listitem">
———. 2026. <span>“Evaluating a Gen<span>AI</span>-Powered Assistive Chatbot for Caseworkers.”</span> Case study. <a href="https://www.navapbc.com/case-studies/evaluating-ai-assistive-chatbot-caseworkers">https://www.navapbc.com/case-studies/evaluating-ai-assistive-chatbot-caseworkers</a>.
</div>
<div id="ref-shanahan2025vita" class="csl-entry" role="listitem">
Shanahan, Catherine, Emma McCarthy, Yan Zhao, Wesley H. Holliday, Jenny Zhao, Janet Ainsworth, and Harry Surden. 2025. <span>“Performance of <span>LLMs</span> on <span>VITA</span> Test: Potential for <span>AI</span>-Assisted Tax Returns for Low Income Taxpayers.”</span> <em>Artificial Intelligence and Law</em>. <a href="https://doi.org/10.1007/s10506-025-09465-7">https://doi.org/10.1007/s10506-025-09465-7</a>.
</div>
<div id="ref-shorten2024structuredrag" class="csl-entry" role="listitem">
Shorten, Connor, Charles Pierse, Thomas Benjamin Smith, Erika Cardenas, Akanksha Sharma, John Trengrove, and Bob van Luijt. 2024. <span>“StructuredRAG: <span>JSON</span> Response Formatting with Large Language Models.”</span> <em>arXiv Preprint arXiv:2408.11061</em>. <a href="https://doi.org/10.48550/arXiv.2408.11061">https://doi.org/10.48550/arXiv.2408.11061</a>.
</div>
<div id="ref-sutherland2023euromod" class="csl-entry" role="listitem">
Sutherland, Holly, Francesco Figari, Ruth Hancock, Manos Matsaganis, Alari Paulus, Iva Tasseva, Alessandra Tumino, and Paola De Agostini. 2023. <span>“<span>EUROMOD</span>: The European Union Tax-Benefit Microsimulation Model.”</span> <em>International Journal of Microsimulation</em>. <a href="https://microsimulation.pub/articles/00075">https://microsimulation.pub/articles/00075</a>.
</div>
<div id="ref-policyengineukdata2026" class="csl-entry" role="listitem">
Woodruff, Nikhil, and Max Ghenis. 2026. <span>“Improving the Accuracy of <span>UK</span> Tax-Benefit Microsimulation with Machine Learning.”</span> PolicyEngine technical paper. <a href="https://policyengine.org/uk_data_enhancement.pdf">https://policyengine.org/uk_data_enhancement.pdf</a>.
</div>
<div id="ref-propel2025snap" class="csl-entry" role="listitem">
ZenML LLMOps Database. 2025. <span>“Building and Automating Comprehensive <span>LLM</span> Evaluation Framework for <span>SNAP</span> Benefits.”</span> Industry writeup. <a href="https://www.zenml.io/llmops-database/building-and-automating-comprehensive-llm-evaluation-framework-for-snap-benefits">https://www.zenml.io/llmops-database/building-and-automating-comprehensive-llm-evaluation-framework-for-snap-benefits</a>.
</div>
<div id="ref-zhou2025tempanswerqa" class="csl-entry" role="listitem">
Zhou, Xinyue et al. 2025. <span>“Time to Revisit Exact Match: Evaluating Temporal Question Answering with Numeric Error Metrics.”</span> <em>arXiv Preprint arXiv:2509.16720</em>. <a href="https://arxiv.org/abs/2509.16720">https://arxiv.org/abs/2509.16720</a>.
</div>
<div id="ref-zhu2021tatqa" class="csl-entry" role="listitem">
Zhu, Fengbin, Wenqiang Lei, Youcheng Huang, Chao Wang, Shujie Zhang, Hongjie Wang, Vincent Chen, et al. 2021. <span>“<span>TAT-QA</span>: A Question Answering Benchmark on a Hybrid of Tabular and Textual Content in Finance.”</span> <em>arXiv Preprint arXiv:2105.07624</em>. <a href="https://arxiv.org/abs/2105.07624">https://arxiv.org/abs/2105.07624</a>.
</div>
</div>

<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
    tabsets.forEach(function(tabset) {
      const tabby = new Tabby('#' + tabset.id);
    });
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'light-border',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>




</body></html>